# theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Yuzhang's Homepage]
description: [<img src="yuzhang.png" width="200">    
Greeting!
]
# Email: yshang4 [AT] hawk [DOT] iit [DOT] edu    
# WeChat: ‘surname’ + ‘given_name’ in Pinyin    
# Address: 15 Yemen Road, Yemen
