# theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Yuzhang Shang]
description: [<img src="yuzhang.png" width="200">
Greeting!]
